server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[format_sql]": true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/api}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8081/api/.well-known/jwks.json}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": orderEvent:com.restaurant.order.dto.OrderEventDTO
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.type.mapping]": orderEvent:com.restaurant.order.dto.OrderEventDTO
        "[spring.json.trusted.packages]": "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    "[com.restaurant.order]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.kafka]": INFO

# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Application Information
info:
  app:
    name: Order Service API
    description: Restaurant Order Management System - Order Service
    version: 1.0.0
